### ISSUE TITLE
Would be nice to support *BSD systems

### ISSUE THREAD

**Issue by TeaM-TL** [moi15moi/FindSystemFontsFilename#21]
I would like to use FindSystemFontsFilename instead fclist-cffi in my project https://github.com/TeaM-TL/FotoKilof 
FotoKilof is used on FreeBSD (has own package) and I need support *BSD systems too

**Comment by moi15moi** [comment]
When you run this piece of code, what is the exception that you get? :
```py
from find_system_fonts_filename import get_system_fonts_filename

fonts_filename = get_system_fonts_filename()
```

**Comment by TeaM-TL** [comment]
```python
>>> from find_system_fonts_filename import get_system_fonts_filename
>>> fonts_filename = get_system_fonts_filename()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tlu/venv/lib/python3.11/site-packages/find_system_fonts_filename/fonts_filename.py", line 39, in get_system_fonts_filename
    return get_system_fonts_class().get_system_fonts_filename()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tlu/venv/lib/python3.11/site-packages/find_system_fonts_filename/fonts_filename.py", line 35, in get_system_fonts_class
    raise OSNotSupported("FindSystemFontsFilename only works on Windows, Mac, Linux and Android.")
find_system_fonts_filename.exceptions.OSNotSupported: FindSystemFontsFilename only works on Windows, Mac, Linux and Android.
```

This output is from FreeBSD 14.1, the same output is on OpenBSD 7.5. Python 3.11

**Comment by moi15moi** [comment]
What is the value of ``system_name`` here?
https://github.com/moi15moi/FindSystemFontsFilename/blob/90c6da97d83aeec9f5e00368c75c02280df1c448/find_system_fonts_filename/fonts_filename.py#L16

From [python doc](https://docs.python.org/3/library/platform.html#platform.system), it should return ``Linux``, but it seems to return something else for you.

**Comment by TeaM-TL** [comment]
```python
>>> from platform import system
>>> system()
'FreeBSD'
```

On OpenBSD result is 'OpenBSD'.


```python
>>> import platform
>>> platform.freedesktop_os_release()
{'NAME': 'FreeBSD', 'ID': 'freebsd', 'PRETTY_NAME': 'FreeBSD 14.1-RELEASE', 'VERSION': '14.1-RELEASE', 'VERSION_ID': '14.1', 'ANSI_COLOR': '0;31', 'CPE_NAME': 'cpe:/o:freebsd:freebsd:14.1', 'HOME_URL': 'https://FreeBSD.org/', 'BUG_REPORT_URL': 'https://bugs.FreeBSD.org/'}
```

**Comment by TeaM-TL** [comment]
may be os will help, because on Macos, Linux and FreeBSD I got the same output:

```python
>>> import os
>>> os.name
'posix'
```

**Comment by moi15moi** [comment]
Ok, so [``platform.system()`` documentation](https://docs.python.org/3/library/platform.html#platform.system) clearly does not list all the possible values (which I thought was the case).

From what I can see [``platform.system()``](https://github.com/python/cpython/blob/16cd6cc86b3ba20074ae3eefb61aeb24ee1544f7/Lib/platform.py#L1063-L1070) call [``platform.uname()``](https://github.com/python/cpython/blob/16cd6cc86b3ba20074ae3eefb61aeb24ee1544f7/Lib/platform.py#L965-L1059) which call ``os.uname()``. ``os.uname()`` seems to be defined like [this](https://github.com/python/cpython/blob/16cd6cc86b3ba20074ae3eefb61aeb24ee1544f7/Modules/posixmodule.c#L6214-L6252), but I don't really understand how it works and the possible returned values aren't [documented](https://docs.python.org/3/library/os.html#os.uname).

> may be os will help, because on Macos, Linux and FreeBSD I got the same output:
> 
> ```python
> >>> import os
> >>> os.name
> 'posix'
> ```

I guess I need to use this approch, but have a special case for Darwin platform since I use CoreText and not fontconfig.

If you run this code, do you have any error?:
```py
from find_system_fonts_filename.linux import LinuxFonts

print(LinuxFonts.get_system_fonts_filename())
```

**Comment by TeaM-TL** [comment]
```python
>>> os.uname()
posix.uname_result(sysname='FreeBSD', nodename='freebsd', release='14.1-RELEASE', version='FreeBSD 14.1-RELEASE releng/14.1-n267679-10e31f0946d8 GENERIC', machine='amd64')
>>> from find_system_fonts_filename.linux import LinuxFonts
>>> print(LinuxFonts.get_system_fonts_filename())
{'/usr/local/share/fonts/urw-base35-fonts/URWBookman-LightItalic.otf', '/usr/local/share/fonts/urw-base35-fonts/NimbusMonoPS-Regular.otf', '/usr/local/share/fonts/urw-base35-fonts/NimbusMonoPS-Bold.ttf', '/usr/local/share/fonts/urw-base35-fonts/StandardSymbolsPS.otf', '/usr/local/share/fonts/urw-base35-fonts/URWGothic-DemiOblique.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusMonoPS-BoldItalic.otf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSans-BoldItalic.otf', '/usr/local/share/fonts/urw-base35-fonts/C059-Roman.otf', '/usr/local/share/fonts/urw-base35-fonts/C059-Roman.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusMonoPS-BoldItalic.ttf', '/usr/local/share/fonts/urw-base35-fonts/URWBookman-Demi.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSans-Bold.ttf', '/usr/local/share/fonts/urw-base35-fonts/P052-BoldItalic.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusRoman-Italic.otf', '/usr/local/share/fonts/urw-base35-fonts/NimbusRoman-BoldItalic.otf', '/usr/local/share/fonts/urw-base35-fonts/P052-Italic.ttf', '/usr/local/share/fonts/urw-base35-fonts/C059-Bold.ttf', '/usr/local/share/fonts/urw-base35-fonts/C059-Italic.otf', '/usr/local/share/fonts/urw-base35-fonts/URWGothic-Demi.otf', '/usr/local/share/fonts/urw-base35-fonts/URWBookman-Light.otf', '/usr/local/share/fonts/urw-base35-fonts/P052-Bold.ttf', '/usr/local/share/fonts/urw-base35-fonts/P052-Italic.otf', '/usr/local/share/fonts/urw-base35-fonts/D050000L.ttf', '/usr/local/share/fonts/urw-base35-fonts/URWGothic-Book.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusRoman-Bold.otf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSans-Italic.otf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSansNarrow-Regular.otf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSansNarrow-BoldOblique.ttf', '/usr/local/share/fonts/urw-base35-fonts/C059-BdIta.otf', '/usr/local/share/fonts/urw-base35-fonts/P052-Roman.ttf', '/usr/local/share/fonts/urw-base35-fonts/URWGothic-DemiOblique.otf', '/usr/local/share/fonts/urw-base35-fonts/NimbusRoman-Bold.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSans-Italic.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSans-Regular.otf', '/usr/local/share/fonts/urw-base35-fonts/URWBookman-Light.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSansNarrow-Bold.ttf', '/usr/local/share/fonts/urw-base35-fonts/D050000L.otf', '/usr/local/share/fonts/urw-base35-fonts/C059-Italic.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSansNarrow-Regular.ttf', '/usr/local/share/fonts/urw-base35-fonts/P052-Bold.otf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSans-BoldItalic.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSansNarrow-Oblique.otf', '/usr/local/share/fonts/urw-base35-fonts/NimbusMonoPS-Regular.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusMonoPS-Italic.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusRoman-Italic.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusRoman-BoldItalic.ttf', '/usr/local/share/fonts/urw-base35-fonts/Z003-MediumItalic.otf', '/usr/local/share/fonts/urw-base35-fonts/C059-BdIta.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSans-Bold.otf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSans-Regular.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSansNarrow-Bold.otf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSansNarrow-BoldOblique.otf', '/usr/local/share/fonts/urw-base35-fonts/NimbusRoman-Regular.otf', '/usr/local/share/fonts/urw-base35-fonts/URWGothic-BookOblique.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusMonoPS-Bold.otf', '/usr/local/share/fonts/urw-base35-fonts/URWGothic-BookOblique.otf', '/usr/local/share/fonts/urw-base35-fonts/C059-Bold.otf', '/usr/local/share/fonts/urw-base35-fonts/URWGothic-Demi.ttf', '/usr/local/share/fonts/urw-base35-fonts/URWBookman-DemiItalic.otf', '/usr/local/share/fonts/urw-base35-fonts/StandardSymbolsPS.ttf', '/usr/local/share/fonts/urw-base35-fonts/URWBookman-Demi.otf', '/usr/local/share/fonts/urw-base35-fonts/NimbusSansNarrow-Oblique.ttf', '/usr/local/share/fonts/urw-base35-fonts/Z003-MediumItalic.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusMonoPS-Italic.otf', '/usr/local/share/fonts/urw-base35-fonts/P052-BoldItalic.otf', '/usr/local/share/fonts/urw-base35-fonts/P052-Roman.otf', '/usr/local/share/fonts/urw-base35-fonts/URWGothic-Book.otf', '/usr/local/share/fonts/urw-base35-fonts/URWBookman-LightItalic.ttf', '/usr/local/share/fonts/urw-base35-fonts/NimbusRoman-Regular.ttf', '/usr/local/share/fonts/urw-base35-fonts/URWBookman-DemiItalic.ttf'}
```

**Comment by TeaM-TL** [comment]
good idea to ask directly Linux fonts!
