### ISSUE TITLE
exception under Win10 32bit and Python3.13

### ISSUE THREAD

**Issue by TeaM-TL** [moi15moi/FindSystemFontsFilename#26]
Python 3.13, Windows 10 32bit, can you reproduce it?

```
C:\Users\TLu\FotoKilof\fotokilof>python
Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 18:47:25) [MSC v.1942 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from find_system_fonts_filename import get_system_fonts_filename
>>> x = get_system_fonts_filename()
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
      x = get_system_fonts_filename()
        File "C:\Users\TLu\AppData\Local\Programs\Python\Python313-32\Lib\site-packages\find_system_fonts_filename\fonts_filename.py", line 40, in get_system_fonts_filename
            return get_system_fonts_class().get_system_fonts_filename()
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
                         File "C:\Users\TLu\AppData\Local\Programs\Python\Python313-32\Lib\site-packages\find_system_fonts_filename\windows\windows_fonts.py", line 135, in get_system_fonts_filename
                             dwrite.DWriteCreateFactory(DWRITE_FACTORY_TYPE.DWRITE_FACTORY_TYPE_ISOLATED, dwrite_factory._iid_, byref(dwrite_factory))
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                 OSError: exception: access violation writing 0x4B5BD838
                                 >>>
```

**Comment by moi15moi** [comment]
Could you update comtypes and tell me if it works?

**Comment by TeaM-TL** [comment]
this is fresh installation with comtypes 1.4.8, doesn't work

**Comment by TeaM-TL** [comment]
I will try to reproduce on more common Windows 11 x64, but I have to find somebody with Windows

**Comment by TeaM-TL** [comment]
I check on the same machine with Python 3.12 and it works

**Comment by moi15moi** [comment]
Thanks!
Then, it is is probably a bug with comtypes. 
I will try to reproduce the error and if I get the same behaviour as you, I will open a issue on comtypes repos.

**Comment by moi15moi** [comment]
I'm able to reproduce the problem, but I have the problem with any x86 version of python.

**Comment by TeaM-TL** [comment]
I will add workaround and use Arial if Windows and Python == 3.13

**Comment by moi15moi** [comment]
I opened a issue on comtypes repos: https://github.com/enthought/comtypes/issues/717
I'm curious about the maintainer opinion.

**Comment by TeaM-TL** [comment]
many thanks!
